// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARz4ClyK03KGwqtcmT890UHrLEFj8UsT0',
    appId: '1:90699955641:web:35b432d43c3bbacfe14a68',
    messagingSenderId: '90699955641',
    projectId: 'weatherapp-4a962',
    authDomain: 'weatherapp-4a962.firebaseapp.com',
    storageBucket: 'weatherapp-4a962.appspot.com',
    measurementId: 'G-TQS05EJDXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnRix-eW896Jhr0f38sflbGQs3TqQdnJE',
    appId: '1:90699955641:android:f4ab731614e48521e14a68',
    messagingSenderId: '90699955641',
    projectId: 'weatherapp-4a962',
    storageBucket: 'weatherapp-4a962.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLI-F13fTEJoajCqDq_6_ViFbDFXr4-zw',
    appId: '1:90699955641:ios:3a8bba4cd383c405e14a68',
    messagingSenderId: '90699955641',
    projectId: 'weatherapp-4a962',
    storageBucket: 'weatherapp-4a962.appspot.com',
    iosBundleId: 'com.example.app',
  );
}
